name: suits
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  awesome_dialog: ^3.3.0
  bloc: ^9.1.0
  cloud_firestore: ^6.0.3
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  cached_network_image: ^3.2.3
  flutter_lints: ^6.0.0
  flutter_svg: ^2.2.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  mailer: ^6.5.0
  meta: ^1.16.0
  pin_code_fields: ^8.0.1
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/signin_icon/
    - assets/textfield_icon/
    - assets/home/
    - assets/category/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/suitsIcon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/category
  output_path: lib/core/utils/
  filename: categort_assets.dart
  field_prefix: null
  ignore_comments: true
